name: dql
description: DQL DSLink
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  quiver: "^0.21.4"
  math_expressions: "^0.2.0+1"
  petitparser: "^1.5.1"
dev_dependencies:
  test: "^0.12.11"
