_diagram = Diagram(
  OneOrMore(
    Choice(
      0,
      Sequence(
        'list',
        OptionalSequence(
          '*',
          '?',
          'path fragment'
        )
      ),
      Sequence(
        'sublist',
        OptionalSequence(
          '*',
          '?',
          'path fragment'
        )
      ),
      Sequence(
        'path',
        'target path'
      ),
      Sequence(
        'filter',
        Sequence(
          Optional('('),
          Sequence(
            Optional(
              Sequence(
                Choice(
                  0,
                  'not'
                ),
                'filter expression'
              )
            ),
            'identifier',
            Optional(
              Choice(
                0,
                Sequence(
                  Choice(
                    0,
                    'or',
                    '||',
                    'and',
                    '&&'
                  ),
                  'filter expression'
                ),
                Sequence(
                  Choice(
                    0,
                    'is',
                    '=',
                    '==',
                    '!=',
                    'equals',
                    'contains',
                    'like',
                    '~',
                    '<',
                    '>',
                    '<=',
                    '>=',
                    'in'
                  ),
                  'value'
                )
              )
            )
          ),
          Optional(')')
        )
      ),
      Sequence(
        'subscribe',
        OneOrMore(
          Sequence(
            Choice(
              0,
              'attribute',
              'column',
              'value',
              'value.timestamp',
              ':name',
              ':displayName',
              '../../metric',
              '../../@attribute',
              '../../:displayName'
            ),
            Optional(
              Sequence(
                'as',
                'column name'
              )
            )
          ),
          Optional(',')
        )
      ),
      Sequence(
        'expression',
        OneOrMore(
          Sequence(
            'column name',
            '=',
            Choice(
              0,
              "row.columnname * 2",
              "Math.random()",
              '"CPU Usage: " + row.columnname'
            )
          )
        )
      ),
      Sequence(
        'drop',
        OneOrMore(
          'column'
        )
      ),
      Sequence(
        'rename',
        OneOrMore(
          Sequence(
            'old name',
            '=',
            'new name'
          )
        )
      ),
      Sequence(
        'invoke',
        Sequence(
          Choice(
            0,
            'actionName',
            '/path/to/action'
          ),
          '(',
          OneOrMore(
            Sequence(
              'paramName',
              '=',
              Choice(
                0,
                '"String"',
                '123',
                '1.23',
                'false',
                'true',
                'null',
                'nil',
                '%columname'
              )
            ),
            ','
          ),
          ')'
        )
      )
    ),
    '|'
  )
);
